dev:
  build: .
  dockerfile: Dockerfile-dev
  command: python manage.py runserver [::]:8000
  env_file: .env
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - postgres
    - memcached
    - redis
postgres:
  image: postgres
  env_file: .env
memcached:
  image: memcached
redis:
  image: redis
